In [14]:
#1) Replace Nan with 0 and Interchange 3 rows and 3 columns of 2D array [[6, -8, 73, -110], [np.nan, -8, 0, 94]]

import numpy as np 
arr=np.array([
    [6, -8, 73, -110], 
    [np.nan, -8, 0, 94]])
print(arr)
print("\nnan->0")
arr = np.nan_to_num(arr, nan=0)
print(arr)
print("\nrows and columns interchange")
arrt=arr.T
print(arrt)

[[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]]

nan->0
[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]

rows and columns interchange
[[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]


In [15]:
#2) Move axes of 3D array to new positions 
import numpy as np

arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print("Original Shape:", arr.shape)
print(arr)

new_arr = np.moveaxis(arr, 0, 2)

print("\nNew Shape:", new_arr.shape)
print(new_arr)

Original Shape: (2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

New Shape: (2, 2, 2)
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [24]:
#3) Replace NaN values with average of columns 
import numpy as np 
arr=np.array([[1,np.nan],[np.nan,4],[3,5]])
print(arr)
arr=np.nan_to_num(arr,nan=np.nanmean(arr,axis=0))
print(arr)


[[ 1. nan]
 [nan  4.]
 [ 3.  5.]]
[[1.  4.5]
 [2.  4. ]
 [3.  5. ]]


In [28]:
# 4) Replace negative value with zero in numpy array using replace
import numpy as np
arr=np.arange(-3,4)
print(arr)

arr = np.where(arr < 0, 0, arr)

print(arr)

[-3 -2 -1  0  1  2  3]
[0 0 0 0 1 2 3]
