In [4]:
#1) Combining a one and a two-dimensional NumPy Array 
import numpy as np 
arr1=np.array([1,2])
arr2=np.array([[3,4],[5,6]])
print("Array 1d:")
print(arr1)
print("Array 2d:")
print(arr2)
result = np.vstack((arr1, arr2))
print("Result Array:")
print(result)

Array 1d:
[1 2]
Array 2d:
[[3 4]
 [5 6]]
Result Array:
[[1 2]
 [3 4]
 [5 6]]


In [5]:
# 2) Flatten a 2d numpy array into 1d array 
import numpy as np
arr=np.array([[1,2],[3,4]])
farr=arr.flatten()
print(farr)

[1 2 3 4]


In [6]:
# 3) Reverse a numpy array 
import numpy as np 
arr=np.array([1,2,3,4])
rarr=arr[::-1]
print("Reverse array:", rarr)

Reverse array: [4 3 2 1]


In [12]:
# 4) Practice operations like 
# -Get the maximum value from given array 
# -Get the minimum value from given array -
# Find the number of rows and columns of a given array -
# using NumPy Select the elements from a given array (each element and specific element)
#  Find the sum of values in a 2D array using for loop
#  Adding, Subtracting, multiplying, dividing arrays in Numpy 

import numpy as np 
arr=np.array([[1,2,3,4,5],[-1,-2,-3,-4,-5]])
maxi=arr.max()
mini=arr.min()
print("Max:",maxi)
print("Min:",mini)
print("rows",arr.shape[0])
print("columns",arr.shape[1])
print(arr) #entire array
print(arr[0]) #first row
print(arr[1][2]) #single element
#loop add
total = 0
for i in arr:
    for j in i:
        total += j
print(total)

#Adding arrays
a = np.array([1,2,3])
b = np.array([4,5,6])
print("a",a)
print("b",b)
print("add")
print(a+b)
#Sub arrays
print("sub")
print(a-b)
#mul arrays
print("mul")
print(a*b)
#div arrays
print("div")
print(a/b)


Max: 5
Min: -5
rows 2
columns 5
[[ 1  2  3  4  5]
 [-1 -2 -3 -4 -5]]
[1 2 3 4 5]
-3
0
a [1 2 3]
b [4 5 6]
add
[5 7 9]
sub
[-3 -3 -3]
mul
[ 4 10 18]
div
[0.25 0.4  0.5 ]


In [ ]:
# 5) Iterate 3D array using for loop and nditer 
import numpy as np
#Loop:
arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
print("Loopimg")
for i in arr:
    for j in i:
        for k in j:
            print(k)
print("Nditer")
#nditer:
for i in np.nditer(arr):
    print(i)

Loopimg
1
2
3
4
5
6
7
8
Nditer
1
2
3
4
5
6
7
8


In [17]:
pip install scipy

   ---------------------------------------- 0.0/37.3 MB ? eta -:--:--
    --------------------------------------- 0.5/37.3 MB 3.2 MB/s eta 0:00:12
   - -------------------------------------- 1.0/37.3 MB 2.7 MB/s eta 0:00:14
   - -------------------------------------- 1.6/37.3 MB 2.5 MB/s eta 0:00:15
   -- ------------------------------------- 2.1/37.3 MB 2.6 MB/s eta 0:00:14
   --- ------------------------------------ 2.9/37.3 MB 2.7 MB/s eta 0:00:13
   ---- ----------------------------------- 3.9/37.3 MB 3.1 MB/s eta 0:00:11
   ----- ---------------------------------- 4.7/37.3 MB 3.3 MB/s eta 0:00:10
   ------ --------------------------------- 5.8/37.3 MB 3.4 MB/s eta 0:00:10
   ------- -------------------------------- 6.6/37.3 MB 3.5 MB/s eta 0:00:09
   ------- -------------------------------- 7.1/37.3 MB 3.5 MB/s eta 0:00:09
   -------- ------------------------------- 8.1/37.3 MB 3.5 MB/s eta 0:00:09
   --------- ------------------------------ 8.7/37.3 MB 3.5 MB/s eta 0:00:09
   ---

In [ ]:
# 6) Study the following program 
# import numpy as np
# # create a numpy 1d-arrays
# arr1 = np.array([3, 4]) 
# arr2 = np.array([1, 0]) 
# # find average of NumPy arrays 
# avg = (arr1 + arr2) / 2 
# print("Average of NumPy arrays:\n", avg) 
# -> Calculate average mean median mode values of two NumPy 2d-arrays

import numpy as np
from scipy import stats

arr1 = np.array([
    [1,2],
    [3,4]
])
arr2 = np.array([
    [5,6],
    [7,3]
])
avg = (arr1 + arr2) / 2
print("Average Array:")
print(avg)
combined = np.concatenate((arr1.flatten(), arr2.flatten()))
print("Mean =", np.mean(combined))
print("Median =", np.median(combined))
print("Mode =", stats.mode(combined, keepdims=True))

Average Array:
[[3.  4. ]
 [5.  3.5]]
Mean = 3.875
Median = 3.5
Mode = ModeResult(mode=array([3]), count=array([2]))
